# -*- coding: utf-8 -*-
"""02_fingerprints_descriptors_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qxzu498b2W_Cdn5h_Mg0xNbJLk9WQ9K-
"""

# Install rdkit
!pip install rdkit
print("rdkit installed")

# =========================
# Feature Engineering Pipeline
# =========================
# This script generates molecular features from SMILES strings, including:
# 1. ECFP4 (Morgan) fingerprints
# 2. Physicochemical descriptors
# 3. Final combined dataset for machine learning

# =========================
# 1. Import Libraries
# =========================
from rdkit import Chem, RDLogger, DataStructs
from rdkit.Chem import AllChem, Descriptors, Lipinski
import pandas as pd
import numpy as np

# Suppress RDKit warnings
RDLogger.DisableLog('rdApp.*')

# =========================
# 2. Load and Prepare Data
# =========================
data = pd.read_csv('01_bioactivity_mps1_clean.csv')

# Convert SMILES to Mol objects
data['Mol'] = data['Smiles'].apply(Chem.MolFromSmiles)

# Remove invalid SMILES
data = data[data['Mol'].notnull()].reset_index(drop=True)

# =========================
# 3. Generate ECFP4 Fingerprints
# =========================
# Morgan fingerprints (ECFP4) capture molecular structure as 2048-bit vectors

fpgen = AllChem.GetMorganGenerator(radius=2, fpSize=2048)

def mol_to_ecfp4(mol):
    fp = fpgen.GetFingerprint(mol)
    arr = np.zeros((2048,), dtype=int)
    DataStructs.ConvertToNumpyArray(fp, arr)
    return arr

# Generate fingerprint matrix
X_fp = np.array(data['Mol'].apply(mol_to_ecfp4).tolist())

# Convert to DataFrame
fp_df = pd.DataFrame(X_fp)

# =========================
# 4. Generate Additional Molecular Descriptors
# =========================
# These descriptors are commonly used in drug discovery

desc_df = pd.DataFrame({
    "TPSA": data['Mol'].apply(Descriptors.TPSA),
    "NumHDonors": data['Mol'].apply(Lipinski.NumHDonors),
    "NumHAcceptors": data['Mol'].apply(Lipinski.NumHAcceptors),
    "NumRotatableBonds": data['Mol'].apply(Lipinski.NumRotatableBonds),
    "NumAromaticRings": data['Mol'].apply(Lipinski.NumAromaticRings)
})

# =========================
# 5. Combine Features into Final Dataset
# =========================

# Add descriptors from original dataset
fp_df['MolecularWeight'] = data['Molecular.Weight'].values
fp_df['AlogP'] = data['AlogP'].values
fp_df['RO5Violations'] = data['X.RO5.Violations'].values

# Add computed descriptors
fp_df = pd.concat([fp_df, desc_df], axis=1)

# Add labels and metadata
fp_df['Activity'] = data['Activity'].values
fp_df['ChEMBL_ID'] = data['Molecule.ChEMBL.ID'].values
fp_df['Smiles'] = data['Smiles'].values

# =========================
# 6. Save Outputs
# =========================

# Save feature arrays
np.save('fingerprints_mps1.npy', X_fp)
np.save('additional_descriptors.npy', desc_df.values)

# Save final dataset
np.save('fingerprints_descriptors_model_dataset.npy', fp_df.values)
fp_df.to_csv('02_fingerprints_descriptors_model_dataset.csv', index=False)

# =========================
# Summary
# =========================
# Generated:
# - ECFP4 fingerprints (2048-bit)
# - Molecular descriptors (TPSA, Lipinski features,...)
# - Final dataset for ML model training