# -*- coding: utf-8 -*-
"""03_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14f61izx9R4DKVxOwgHrqGQ54rs1ekreM
"""

# =========================
# Exploratory Data Analysis (EDA)
# =========================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA

# Clean plotting style (no grid)
sns.set(style="white")

# -------------------------
# 1. Load Data
# -------------------------
data = pd.read_csv("02_fingerprints_descriptors_model_dataset.csv")

# Convert Activity to readable labels
data["Activity"] = data["Activity"].map({0: "Inactive", 1: "Active"})

print(data.head())


# -------------------------
# 2. Class Distribution
# -------------------------
plt.figure(figsize=(6,4))

sns.countplot(
    x="Activity",
    data=data,
    palette={"Inactive": "red", "Active": "blue"},
    order=["Inactive", "Active"]
)

plt.title("Distribution of Bioactivity Classes")
plt.xlabel("Bioactivity Class")
plt.ylabel("Number of Compounds")

plt.tight_layout()
plt.savefig("activity_distribution.png", dpi=300)
plt.show()

print("\nClass distribution (%):")
print((data["Activity"].value_counts(normalize=True) * 100).round(2))


# -------------------------
# 3. Physicochemical Analysis
# -------------------------
data["RO5_compliant"] = data["RO5Violations"] == 0

summary_table = data.groupby("Activity").agg(
    MW_mean=("MolecularWeight", "mean"),
    MW_median=("MolecularWeight", "median"),
    AlogP_mean=("AlogP", "mean"),
    AlogP_median=("AlogP", "median"),
    RO5_percent=("RO5_compliant", lambda x: x.mean() * 100)
)

print("\nPhysicochemical Summary:")
print(summary_table)

summary_table.to_csv("physchem_summary_table.csv")


# -------------------------
# 4. Statistical Summary
# -------------------------
print("\nFeature Skewness:")
print(data[["MolecularWeight", "AlogP", "RO5Violations"]].skew())

corr = data[["MolecularWeight", "AlogP", "RO5Violations"]].corr()

plt.figure(figsize=(6,5))
sns.heatmap(corr, annot=True, cmap="coolwarm", fmt=".2f")

plt.title("Descriptor Correlation Heatmap")

plt.tight_layout()
plt.savefig("correlation_heatmap.png", dpi=300)
plt.show()


# -------------------------
# 5. Chemical Space Visualization
# -------------------------
plt.figure(figsize=(7,5))

sns.scatterplot(
    data=data,
    x="MolecularWeight",
    y="AlogP",
    hue="Activity",
    palette={"Inactive": "red", "Active": "green"},
    alpha=0.7
)

plt.title("Chemical Space of MPS1 Compounds")
plt.xlabel("Molecular Weight")
plt.ylabel("AlogP (Lipophilicity)")

plt.tight_layout()
plt.savefig("chemical_space.png", dpi=300)
plt.show()


# Boxplots
fig, axes = plt.subplots(1, 2, figsize=(10,4))

sns.boxplot(data=data, x="Activity", y="MolecularWeight", ax=axes[0])
axes[0].set_title("MW by Activity")

sns.boxplot(data=data, x="Activity", y="AlogP", ax=axes[1])
axes[1].set_title("AlogP by Activity")

plt.tight_layout()
plt.savefig("boxplots_descriptors.png", dpi=300)
plt.show()


# -------------------------
# 6. Fingerprint PCA Analysis
# -------------------------

# Extract fingerprint columns (0–2047)
fp_cols = [col for col in data.columns if col.isdigit()]
X_fp = data[fp_cols].values

# PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_fp)

pca_df = pd.DataFrame({
    "PC1": X_pca[:, 0],
    "PC2": X_pca[:, 1],
    "Activity": data["Activity"]
})

plt.figure(figsize=(7,5))

sns.scatterplot(
    data=pca_df,
    x="PC1",
    y="PC2",
    hue="Activity",
    palette={"Inactive": "red", "Active": "green"},
    alpha=0.6
)

plt.title(
    f"PCA of ECFP4 Fingerprints\n"
    f"PC1: {pca.explained_variance_ratio_[0]*100:.1f}% | "
    f"PC2: {pca.explained_variance_ratio_[1]*100:.1f}%"
)

plt.tight_layout()
plt.savefig("pca_fingerprints.png", dpi=300)
plt.show()