# -*- coding: utf-8 -*-
"""04_modeling_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_3VLGckohuKTLeoAsYMdBKPL93K8Zck-
"""

#Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, roc_curve

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from xgboost import XGBClassifier

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# =========================
# Load Data
# =========================

data = pd.read_csv("02_fingerprints_descriptors_model_dataset.csv")

#Define X/y
X = data.drop(columns=['Activity', 'ChEMBL_ID', 'Smiles'])
X = X.select_dtypes(include=[np.number])

y = data['Activity']

# =========================
# Train/Test Split
# =========================
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,    # 20% test, 80% train
    stratify=y,       # keep same ratio of actives/inactives
    random_state=42   # reproducible
)

print("Training shape:", X_train.shape)
print("Test shape:", X_test.shape)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# =========================
# Helper function
# =========================
def evaluate(name, y_test, y_proba, y_pred):
    print("\n====================")
    print(name)
    print("====================")

    print(classification_report(y_test, y_pred))

    auc = roc_auc_score(y_test, y_proba)
    print("ROC-AUC:", auc)

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    return auc, y_proba

# =========================
# 1. Logistic Regression
# =========================
model_lr = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])


# Cross-validation
cv_scores_lr = cross_val_score(
    model_lr,
    X_train,
    y_train,
    cv=cv,
    scoring="roc_auc"
)

print("\nLogistic Regression CV ROC-AUC:", cv_scores_lr)
print("Mean:", cv_scores_lr.mean())

# Fit + Evaluate
model_lr.fit(X_train, y_train)

y_proba_lr = model_lr.predict_proba(X_test)[:, 1]
y_pred_lr = model_lr.predict(X_test)


auc_lr, y_proba_lr = evaluate("Logistic Regression", y_test, y_proba_lr, y_pred_lr)

# =========================
# 2. Random Forest
# =========================
model_rf = RandomForestClassifier(
    n_estimators=200,
    class_weight="balanced",
    random_state=42
)

# Cross-validation
cv_scores_rf = cross_val_score(model_rf, X_train, y_train, cv=cv, scoring="roc_auc")

print("\nRandom Forest CV ROC-AUC:", cv_scores_rf)
print("Mean:", cv_scores_rf.mean())

# Fit + Evaluate
model_rf.fit(X_train, y_train)

y_proba_rf = model_rf.predict_proba(X_test)[:, 1]
y_pred_rr = model_lr.predict(X_test)

auc_rf, y_proba_rf = evaluate("Random Forest", y_test, y_proba_rf, y_pred_rf)


# =========================
# 3. XGBoost
# =========================
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

model_xgb = XGBClassifier(
    n_estimators=200,
    max_depth=5,
    learning_rate=0.1,
    scale_pos_weight=scale_pos_weight,
    eval_metric="logloss",
    random_state=42
)

# Cross-validation
cv_scores_xgb = cross_val_score(model_xgb, X_train, y_train, cv=cv, scoring="roc_auc")

print("\nXGBoost CV ROC-AUC:", cv_scores_xgb)
print("Mean:", cv_scores_xgb.mean())

# Fit + Evaluate
model_xgb.fit(X_train, y_train)

y_proba_xgb = model_xgb.predict_proba(X_test)[:, 1]
y_pred_lr = model_xgb.predict(X_test)

auc_xgb, y_proba_xgb = evaluate("XGBoost", y_test, y_proba_xgb, y_pred_xgb)

# =========================
# 4. SVM
# =========================
model_svm = Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC(probability=True, class_weight="balanced"))
])

# Cross-validation
cv_scores_svm = cross_val_score(model_svm, X_train, y_train, cv=cv, scoring="roc_auc")

print("\nSVM CV ROC-AUC:", cv_scores_svm)
print("Mean:", cv_scores_svm.mean())

# Fit + Evaluate
model_svm.fit(X_train, y_train)

y_proba_svm = model_svm.predict_proba(X_test)[:, 1]
y_pred_lr = model_svm.predict(X_test)

auc_svm, y_proba_svm = evaluate("SVM", y_test, y_proba_svm, y_pred_svm)

# =========================
# 5. ROC-AUC comparison
# =========================
print("\n====================")
print("ROC-AUC SUMMARY")
print("====================")

print("LogReg:", roc_auc_score(y_test, y_proba_lr))
print("RF:", roc_auc_score(y_test, y_proba_rf))
print("XGB:", roc_auc_score(y_test, y_proba_xgb))
print("SVM:", roc_auc_score(y_test, y_proba_svm))

# =========================
# ROC Curve for Comparison
# =========================

# Store predictions
results = {
    "LogReg": y_proba_lr,
    "RF": y_proba_rf,
    "XGBoost": y_proba_xgb,
    "SVM": y_proba_svm
}


plt.figure(figsize=(6,5))

for name, y_proba in results.items():
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    auc = roc_auc_score(y_test, y_proba)
    plt.plot(fpr, tpr, label=f"{name} (AUC = {auc:.3f})")

# Baseline
plt.plot([0,1], [0,1], linestyle='--')

# Labels
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")

plt.legend(fontsize=9)
plt.tight_layout()

plt.savefig("roc_comparison.png", dpi=300, bbox_inches="tight")
plt.show()

# =========================
# Confusion Matrix Plot
# =========================
import seaborn as sns

predictions = {
    "LogReg": y_pred_lr,
    "RF": y_pred_rf,
    "XGBoost": y_pred_xgb,
    "SVM": y_pred_svm
}

for name, y_pred in predictions.items():
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(4,4))
    sns.heatmap(
        cm,
        annot=True,
        fmt='d',
        cmap='Blues',
        cbar=False,
        xticklabels=["Inactive", "Active"],
        yticklabels=["Inactive", "Active"]
    )

    plt.title(f"{name} Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")

    plt.tight_layout()
    plt.savefig(f"cm_{name}.png", dpi=300, bbox_inches="tight")
    plt.show()