# -*- coding: utf-8 -*-
"""05_final_model_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sciLzbQgwDEpGywqXMgW_eBRbunWQtjP
"""

"""
Pipeline:
1. XGBoost selected based on highest ROC-AUC from prior comparison
2. Hyperparameters tuned using GridSearchCV
3. Classification threshold optimization
4. Final evaluation
"""

# =========================
# 1. Import Libraries
# =========================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import shap
import seaborn as sns

from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV
from sklearn.metrics import classification_report, roc_auc_score, confusion_matrix, precision_recall_curve
from xgboost import XGBClassifier


# =========================
# 2. Load + Split
# =========================
data = pd.read_csv("02_fingerprints_descriptors_model_dataset.csv")

X = data.drop(columns=['Activity', 'ChEMBL_ID', 'Smiles'])
X = X.select_dtypes(include=[np.number])
y = data['Activity']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

# Validation set for threshold tuning
X_train_sub, X_val, y_train_sub, y_val = train_test_split(
    X_train, y_train,
    test_size=0.2,
    stratify=y_train,
    random_state=42
)

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# =========================
# 3. GridSearch XGBoost
# =========================
param_grid = {
    'learning_rate': [0.05, 0.1],
    'max_depth': [3, 5],
    'n_estimators': [200, 300]
}

xgb = XGBClassifier(
    scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum(),
    eval_metric='logloss',
    random_state=42
)

grid = GridSearchCV(
    xgb,
    param_grid,
    cv=cv,
    scoring='roc_auc',
    n_jobs=-1,
    verbose=1
)

grid.fit(X_train_sub, y_train_sub)
best_model = grid.best_estimator_

print("\n====================")
print("GridSearch Model")
print("====================")
print("Best Params:", grid.best_params_)

# =========================
# 4. GridSearch Model Evaluation
# =========================
y_grid_proba = best_model.predict_proba(X_test)[:, 1]
y_grid_pred_05 = (y_grid_proba >= 0.5).astype(int)

print("\n====================")
print("GridSearch Performance")
print("====================")

print("ROC-AUC:", roc_auc_score(y_test, y_grid_proba))
print(classification_report(y_test, y_grid_pred_05))
print(confusion_matrix(y_test, y_grid_pred_05))


# =========================
# 5. Threshold Optimization
# =========================
y_val_proba = best_model.predict_proba(X_val)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_val, y_val_proba)

f1_scores = 2 * precisions * recalls / (precisions + recalls + 1e-8)

best_t = thresholds[np.argmax(f1_scores[:-1])] if len(thresholds) > 0 else 0.5

print("\n====================")
print("Threshold Optimization")
print("====================")
print("Default threshold: 0.5")
print("Optimized threshold:", best_t)


# =========================
# 6. Final Model Evaluation
# =========================
y_test_proba = best_model.predict_proba(X_test)[:, 1]
y_test_pred_opt = (y_test_proba >= best_t).astype(int)

print("\n====================")
print("Final Model")
print("====================")

print("ROC-AUC:", roc_auc_score(y_test, y_test_proba))
print(classification_report(y_test, y_test_pred_opt))
print(confusion_matrix(y_test, y_test_pred_opt))

cm = (confusion_matrix(y_test, y_test_pred_opt))
print(cm)

# =========================
# 7. Confusion Matrix Plot
# =========================
plt.figure(figsize=(4,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix (XGBoost Final)")
plt.tight_layout()
plt.savefig("confusion_matrix_xgb.png", dpi=300)
plt.show()

# =========================
# 8. Save Model + Threshold
# =========================
import joblib
joblib.dump(best_model, "model_final_xgb.pkl")
np.save("best_threshold.npy", best_t)

# =========================
# 9. Feature Importance (Descriptors)
# =========================
n_desc = 8
desc_names = [
    'Molecular.Weight', 'AlogP', 'X.RO5.Violations', 'TPSA',
    'NumHDonors', 'NumHAcceptors', 'NumRotatableBonds', 'NumAromaticRings'
]

importances = best_model.feature_importances_
importances_desc = importances[-n_desc:]

desc_pairs = sorted(zip(desc_names, importances_desc), key=lambda x: x[1], reverse=True)

names_sorted = [x[0] for x in desc_pairs]
values_sorted = [x[1] for x in desc_pairs]

plt.figure(figsize=(6,4))
plt.barh(names_sorted, values_sorted)
plt.xlabel("Feature Importance")
plt.title("Descriptor Importance (Final XGBoost)")
plt.gca().invert_yaxis()
plt.tight_layout()
plt.savefig('feature_importance_final_xgb.png', dpi=300)
plt.show()

# =========================
# 10. SHAP Summary Plot
# =========================
explainer = shap.TreeExplainer(best_model)
shap_values = explainer.shap_values(X_test)

X_test_desc = X_test.iloc[:, -n_desc:]
shap_values_desc = shap_values[:, -n_desc:]

shap.summary_plot(
    shap_values_desc,
    X_test_desc,
    feature_names=desc_names,
    show=False
)

plt.savefig("shap_final_xgb_desc.png", dpi=300, bbox_inches="tight")
plt.show()